INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC  ;IF A NUMBER IS NEG OR POSITIVE 
    MOV BX,-9
    CMP BX,0;COMPARE
    JL IF
    JGE ELSE
    IF:  
    PRINTN "THE NUMBER IS NEGATIVE" 
    JMP ENDIF
    
    ELSE:
    PRINTN "THE NUMBER IS POSITIVE"
    JMP ENDIF   
    ENDIF: 
    
    MOV AH,4CH
    INT 21H
        
MAIN ENDP
END MAIN