.MODEL SMALL
.STACK 100H
.DATA
    
    MSG DB 'HELLO WORLD$'
    MSG2 DB 'THIS IS FUN REALLY$'

.CODE

MAIN PROC
    
    MOV AX, @DATA  ;DATA SEGMENT NUMBER DEFINED BY .DATA IS MOVED TO AX
    MOV DS, AX     ;THAT NUMBER IS MOVED TO THE SEGMENT REGISTER
    
    
    LEA DX, MSG    ; LOAD THE MESSAGE IN THE DX REGISTER
    MOV AH, 9      ; DISPLAY STRING FUNCTION
    INT 21H        ; EXECUTE THE DISPLAY STRING FUNCTION
    
    ; NEW LINE
    
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    LEA DX, MSG2
    MOV AH, 9
    INT 21H
    
    ;RETURN TO DOS
    
    MOV AH, 4CH
    INT 21H
    
MAIN ENDP

    END MAIN